### ISSUE TITLE
Descrição no README

### ISSUE THREAD

**Issue by gabrielfern** [joaohenriquedss/PointDaBebida#2]
Queria deixar como sugestão por uma descrição
do que é o projeto no README, tipo:

O PointDaBebida é uma aplicação web que tem
por objetivo ser uma loja de bebidas online, onde o cliente
pode isso blablabla, etc...

**Comment by joaohenriquedss** [comment]
Entendi , irei trabalhar nessas melhoras. Obrigado pela dica
