### ISSUE TITLE
Trocar 'index' como nome dos métodos de requisições get

### ISSUE THREAD

**Issue by jardely** [joaohenriquedss/PointDaBebida#4]
Primeiramente, achei seu projeto muito bom e organizado. A sugestão que faço, é trocar o nome dos métodos das requisições get. Talvez eu não esteja habituada a isso, mas usar 'index' como nome me parece estranho. Talvez usar getUsers, getCategory, por exemplo, melhora a legibilidade.

**Comment by joaohenriquedss** [comment]
Bom Dia , obrigado pela dica irei ajustar essas questões
