### ISSUE TITLE
Dica: Nome dos componentes

### ISSUE THREAD

**Issue by lucasvictor3** [joaohenriquedss/PointDaBebida#5]
https://github.com/joaohenriquedss/PointDaBebida/blob/b72752b9b3d9f5a03957ebbb270d7f590fc161b0/frontend/src/components/Header/index.js#L2

Boa tarde João, uma sugestão é manter os nomes dos arquivos dos componentes iguais ao nome do componente em si, no caso acima, seria Header.js e .css, até pra facilitar o entendimento do path quando for importado em outro arquivo.

**Comment by joaohenriquedss** [comment]
Boa Noite, Obrigado pela dica
