### ISSUE TITLE
Melhorar nomes de componentes e hooks

### ISSUE THREAD

**Issue by jardely** [joaohenriquedss/PointDaBebida#7]
Oi, João! Sugiro que você mude o nome do componente 'setCategory' me parece mais nome de função. A mesma coisa pro getProduct, mas como me parece ser um hook, mudaria pra algo como useProducts ou até mesmo useGetProducts, assim fica mais claro. No mais, seu projeto está muito bom 👏

**Comment by joaohenriquedss** [comment]
Obrigado , pela dica. Irei organizar essas mudanças
