### ISSUE TITLE
Uso do useEffect

### ISSUE THREAD

**Issue by douglaslimaxx** [joaohenriquedss/PointDaBebida#8]
Eu percebi que tu está usando um componentDidMount para mudar o estado ao pegar os dados, seria massa tu dar uma olhada no [useEffect](https://www.digitalocean.com/community/tutorials/react-replacing-component-lifecycles-with-useeffect) pois ele é bem mais simples e funciona tanto para montagem como para atualização de um componente.

**Comment by joaohenriquedss** [comment]
Obrigado , eu não sabia o que colocar fora componentDidMount. Mas tu avisando já sei que funciona e vou colocar.
