### ISSUE TITLE
centralizar componentes do login

### ISSUE THREAD

**Issue by g1ovanaqueiroz** [joaohenriquedss/PointDaBebida#9]
Oi João, projeto tá top como sempre. Mas acho que seria boa ideia tentar centralizar melhor os elementos da tela de login.
Você é top, jaum. ^^

**Comment by joaohenriquedss** [comment]
Obrigado , eu to tentando mas css ta me matando kkkkk

**Comment by g1ovanaqueiroz** [comment]
CSS sendo CSS kskskasdk
